### ISSUE TITLE
Commiting IDEA configuration files is a bad practice

### ISSUE THREAD

**Issue by jrfaller** [aneopsy/HQSE_1#2]

**Comment by nonnenp** [comment]
https://github.com/aneopsy/HQSE_1/commit/0665da60f6cb3b14741d61b3b879029052674c6b fixed this issue.

**Comment by jrfaller** [comment]
Don't forget to learn auto closing issues : https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
