### ISSUE TITLE
Commiting gradle temporary files is a bad practice

### ISSUE THREAD

**Issue by jrfaller** [aneopsy/HQSE_1#3]

**Comment by nonnenp** [comment]
https://github.com/aneopsy/HQSE_1/commit/e48a7bd1aba56058282d53b21a21c9d7246f9536 fixed this issue, Close#3

**Comment by aneopsy** [comment]
Fixed in commit: https://github.com/aneopsy/HQSE_1/commit/0665da60f6cb3b14741d61b3b879029052674c6b

**Comment by jrfaller** [comment]
Dont forget to learn how to auto close issues : https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
