### ISSUE TITLE
Displaying a build status badge in your project README increase confidence of users

### ISSUE THREAD

**Issue by jrfaller** [aneopsy/HQSE_1#8]
See https://docs.travis-ci.com/user/status-images/

**Comment by aneopsy** [comment]
Added in https://github.com/aneopsy/HQSE_1/commit/44d514e1f097f26e30bf57c36fe3aa25237ea366

**Comment by jrfaller** [comment]
Nice! But don't forget to learn to auto-close issues,  it's much faster :)
